### ISSUE TITLE
Inquiry about Shortcut Key Functionality

### ISSUE THREAD

**Issue by chendongde310** [barsdeveloper/ueblueprint#10]
I would like to inquire if the functionality to disconnect connections is working properly. I am unable to disconnect any connections between nodes unless I delete the blueprint node itself.

**Comment by barsdeveloper** [comment]
You can double click on a arc to create a path node (don't remember the exact name) and delete that one. Is there a shortcut key in UE?

**Comment by chendongde310** [comment]
Yes, you can disconnect by pressing ALT + left mouse click.


---Original---
From: ***@***.***&gt;
Date: Fri, Aug 4, 2023 16:59 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [barsdeveloper/ueblueprint] Inquiry about Shortcut KeyFunctionality (Issue #10)




 
You can double click on a arc to create a path node (don't remember the exact name) and delete that one. Is there a shortcut key in UE?

**Comment by barsdeveloper** [comment]
Will add it. Thanks
