### ISSUE TITLE
Blueprint recognition error

### ISSUE THREAD

**Issue by chendongde310** [barsdeveloper/ueblueprint#11]
The following material blueprint is incorrectly identified

 
# First paragraph

`
Begin Object Class=/Script/UnrealEd.MaterialGraphNode Name="MaterialGraphNode_35" ExportPath=/Script/UnrealEd.MaterialGraphNode'"/Engine/Transient.EasyMaterial_UVsTools:MaterialGraph_0.MaterialGraphNode_35"'
   Begin Object Class=/Script/Engine.MaterialExpressionNamedRerouteDeclaration Name="MaterialExpressionNamedRerouteDeclaration_0" ExportPath=/Script/Engine.MaterialExpressionNamedRerouteDeclaration'"/Engine/Transient.EasyMaterial_UVsTools:MaterialGraph_0.MaterialGraphNode_35.MaterialExpressionNamedRerouteDeclaration_0"'
   End Object
   Begin Object Name="MaterialExpressionNamedRerouteDeclaration_0" ExportPath=/Script/Engine.MaterialExpressionNamedRerouteDeclaration'"/Engine/Transient.EasyMaterial_UVsTools:MaterialGraph_0.MaterialGraphNode_35.MaterialExpressionNamedRerouteDeclaration_0"'
      Input=(Expression=/Script/Engine.MaterialExpressionStaticSwitchParameter'"MaterialGraphNode_57.MaterialExpressionStaticSwitchParameter_0"')
      Name="UV"
      NodeColor=(R=1.000000,G=0.000000,B=0.539062,A=1.000000)
      VariableGuid=29FFD1C646173F67F8E92E9668749B30
      MaterialExpressionEditorX=-2448
      MaterialExpressionEditorY=128
      MaterialExpressionGuid=533D1F4F4A59D278A942739755076DED
      Material=/Script/UnrealEd.PreviewMaterial'"/Engine/Transient.EasyMaterial_UVsTools"'
   End Object
   MaterialExpression=/Script/Engine.MaterialExpressionNamedRerouteDeclaration'"MaterialExpressionNamedRerouteDeclaration_0"'
   NodePosX=-2448
   NodePosY=128
   bCanRenameNode=True
   NodeGuid=DD6403B44F32F513B6710DA7C7CA287B
   CustomProperties Pin (PinId=467497C34BC6BF382A785995D2759F75,PinName="Input",PinFriendlyName=NSLOCTEXT("MaterialGraphNode", "Space", " "),PinType.PinCategory="required",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(MaterialGraphNode_57 B769B4D24EDF22AFE13C7983ECABE908,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=0719806040CBE71DF7BCF69007052361,PinName="Output",PinFriendlyName=NSLOCTEXT("MaterialGraphNode", "Space", " "),Direction="EGPD_Output",PinType.PinCategory="",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
`

# Second paragraph

`
Begin Object Class=/Script/UnrealEd.MaterialGraphNode Name="MaterialGraphNode_20" ExportPath=/Script/UnrealEd.MaterialGraphNode'"/Engine/Transient.EasyMaterial_UVsTools:MaterialGraph_0.MaterialGraphNode_20"'
   Begin Object Class=/Script/Engine.MaterialExpressionComponentMask Name="MaterialExpressionComponentMask_0" ExportPath=/Script/Engine.MaterialExpressionComponentMask'"/Engine/Transient.EasyMaterial_UVsTools:MaterialGraph_0.MaterialGraphNode_20.MaterialExpressionComponentMask_0"'
   End Object
   Begin Object Name="MaterialExpressionComponentMask_0" ExportPath=/Script/Engine.MaterialExpressionComponentMask'"/Engine/Transient.EasyMaterial_UVsTools:MaterialGraph_0.MaterialGraphNode_20.MaterialExpressionComponentMask_0"'
      Input=(Expression=/Script/Engine.MaterialExpressionTextureSampleParameter2D'"MaterialGraphNode_23.MaterialExpressionTextureSampleParameter2D_2"',Mask=1,MaskR=1,MaskG=1,MaskB=1)
      R=True
      MaterialExpressionEditorX=-864
      MaterialExpressionEditorY=1776
      MaterialExpressionGuid=B8BA777C460A98B7822F60AF1EAD8D96
      Material=/Script/UnrealEd.PreviewMaterial'"/Engine/Transient.EasyMaterial_UVsTools"'
   End Object
   MaterialExpression=/Script/Engine.MaterialExpressionComponentMask'"MaterialExpressionComponentMask_0"'
   NodePosX=-864
   NodePosY=1776
   AdvancedPinDisplay=Hidden
   NodeGuid=7D9E07084DA9D1F17AD6B593D98279F3
   CustomProperties Pin (PinId=DE9477874ADEED2F1E0339873642F266,PinName="Input",PinFriendlyName=NSLOCTEXT("MaterialGraphNode", "Space", " "),PinType.PinCategory="required",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(MaterialGraphNode_23 21F5570B4FF8AAD2E46EECB635791270,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
   CustomProperties Pin (PinId=086DF7D3437164BE0A9220961AB98A5C,PinName="R",PinType.PinCategory="optional",PinType.PinSubCategory="bool",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="true",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=True,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=True,bOrphanedPin=False,)
   CustomProperties Pin (PinId=1B8CAF90401F9C76C4BF3C8E0411E6AB,PinName="G",PinType.PinCategory="optional",PinType.PinSubCategory="bool",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=True,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=True,bOrphanedPin=False,)
   CustomProperties Pin (PinId=B61343EF4929A6112E6F38B8D35AA6B4,PinName="B",PinType.PinCategory="optional",PinType.PinSubCategory="bool",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=True,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=True,bOrphanedPin=False,)
   CustomProperties Pin (PinId=A68FA2EB46ADA25F20F873AA79F33F0E,PinName="A",PinType.PinCategory="optional",PinType.PinSubCategory="bool",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,DefaultValue="false",PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=True,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=True,bOrphanedPin=False,)
   CustomProperties Pin (PinId=82EDBF3A444095054CF02AA013915100,PinName="Output",PinFriendlyName=NSLOCTEXT("MaterialGraphNode", "Space", " "),Direction="EGPD_Output",PinType.PinCategory="",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.PinSubCategoryMemberReference=(),PinType.PinValueType=(),PinType.ContainerType=None,PinType.bIsReference=False,PinType.bIsConst=False,PinType.bIsWeakPointer=False,PinType.bIsUObjectWrapper=False,PinType.bSerializeAsSinglePrecisionFloat=False,LinkedTo=(MaterialGraphNode_3 9A414D2A454C08C93ED83B88163A9B44,),PersistentGuid=00000000000000000000000000000000,bHidden=False,bNotConnectable=False,bDefaultValueIsReadOnly=False,bDefaultValueIsIgnored=False,bAdvancedView=False,bOrphanedPin=False,)
End Object
`

**Comment by barsdeveloper** [comment]
Hello, I'm checking the first node. What is it more exactly? Can you get me the properly formatted text copied/pasted from the editor? In the second sub object I see Name attribute twice, I've never seen it in any node I've tried so far building this library.

**Comment by barsdeveloper** [comment]
I'm closing it for now. Please feel free to open it again in case you face this issue or open another one. Thanks
