### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by juntaosun** [barsdeveloper/ueblueprint#8]
> ueblueprint@1.0.0 build
> rollup --config && sass scss/export.scss:dist/css/ueb-style.css && sass scss/export.scss:dist/css/ueb-style.min.css --style=compressed

(node:752) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
[!] RollupError: Node tried to load your configuration file as CommonJS even though it is likely an ES module. To resolve this, change the extension of your configuration to ".mjs", set "type": "module" in your package.json file or pass the "--bundleConfigAsCjs" flag.

Original error: Cannot use import statement outside a module
https://rollupjs.org/command-line-interface/#bundleconfigascjs
D:\OtherGithub\ueblueprint\rollup.config.js:1
import commonjs from "@rollup/plugin-commonjs"
^^^^^^

**Comment by barsdeveloper** [comment]
Hi, can you give more context, like what is your OS, node version etc?
Also did you you the following commands?
npm install
npm run build

**Comment by barsdeveloper** [comment]
Dependencies install was not working due to a conflict of the Rollup version specified in package.json. Please try again.

**Comment by juntaosun** [comment]
it works, thanks
