### ISSUE TITLE
Feedback and Questions about the Blueprint Viewer Project

### ISSUE THREAD

**Issue by chendongde310** [barsdeveloper/ueblueprint#9]
This is not a question, I just wanted to let you know that this is a very interesting project and a great solution for viewing blueprints outside of Unreal Engine (even being able to edit them). I look forward to future updates.

At the same time, I have some questions about future updates:

Will you add the ability to create nodes (instead of copy-pasting)? I understand that this would be a significant undertaking.
Keyboard shortcuts for node linking and unlinking (e.g., Alt + left mouse click).
Support for editing nodes in Material Blueprints.

**Comment by barsdeveloper** [comment]
Hi, thanks for the interest. I thought about it but and would like to try at some point but I'm not sure it is feasible. Basically there would be two possible approaches: one is to have a large amount of metadata that gives information about all the available nodes, types, pins etc; another would be to access directly the source code of the engine and static analyze it. Both would require the use of some tool like LLVM but then again probably most of the information you can find only after instantiating the CDO (Class Defaut Object) which means running some C++ code. Unless there is some more straight forward way I'm not aware of, I don't think it would be possible.
